### ISSUE TITLE
Unable to recreate the application

### ISSUE THREAD

**Issue by zipzit** [mtobeiyf/keras-flask-deploy-webapp#35]
I've been struggling for hours trying to get this sample to build and run.  

Docker container works great, and let's me easily see what this program does.  In fact I can shell into the running docker container and verify the python/pip setup, as well as the tooling listed in the requirements.txt.  I can verify that the docker container is using python 3.6.12 and pip 21.0.1

I did a whole lot of testing, and unless I had python 3.6.12 AND pip 21.0.1 I could not get a pass on `pip install -r requirements.txt`

Consider this an issue raised.   You absolutely have to have Python version 3.6.12 and pip version 21.0.1 to successfully reproduce this sample.  Can I recommend that info be added to the coversheet README.md file?  In fact, that might be a good action to take to close this open issue.  

Note: I used [pyenv for managing the python versions...](https://realpython.com/intro-to-pyenv/)   After bringing Python to 3.6.12 I then had to  `$  pip install --upgrade pip` (which brought pip from 18.1 to 21.0.1)

Many thanks for sharing this repo. You've helped me a whole lot understand classification within python

**Comment by mtobeiyf** [comment]
What's the error message when you run `pip install -r requirements.txt`? 
I've updated the tensorflow version, could you try again with the latest repo?

**Comment by zipzit** [comment]
Huh?  Where are you going with this? I'm not high end Python user, but this repo / example is a snapshot, moment in time thing.  I wouldn't expect the same code to run the same for the next 20 years, to match version updates with code around it.   With that said... You absolutely must include your `$ python -V` and `$ pip -V` version information to mate to requirements.txt.  Suggestion.. If you are going to chase version stuff, that's great, BUT you really need to add the testbed Python version and Pip version info as `#` comments within the requirements.txt file each and every time you make a repo change.  

The fact that you mention "latest repo" withOUT once mentioning what versions of Python / Pip you are using doesn't sell well.    But here, you are welcome to rerun the experiment.  I'll upload my vagrantfile here.  (Note you might have to make adjustments for shared folder, # of cpus and memory size, but that should get you started. Its a Ubuntu 20.04 virtualbox setup, but with camera, microphone and audio out support). 

[Vagrantfile_removeme.txt](https://github.com/mtobeiyf/keras-flask-deploy-webapp/files/5985073/Vagrantfile_removeme.txt)
You will need virtualbox and vagrant installed on your computer.  `vagrant up` starts the journey.  

Again, many thanks for what you've shared here.  No offense with my comments.. My thought is nobody else in the future needs to be punished (by spending hours) trying to figure out which versions of stuff work with which......   Keep it simple, make it easy and fun.

**Comment by mtobeiyf** [comment]
I get what you mean. This repo do provide [Dockerfile](https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/master/Dockerfile) which is quite similar to vagrant, and in the README, I mentioned [Run with Docker](https://github.com/mtobeiyf/keras-flask-deploy-webapp/blob/master/README.md#run-with-docker) at the first place, it should pull a docker image, which is just like a virtual machine with Python in fixed version. Anyone could reproduce the app in minutes. 

I understand it would be good to provide a specific Python/Pip version in the repo. However, different users have different local environments, it's not a good idea to suggest a specific version and let the users mess up their local environment. That's why the Docker is needed, just like vagrant you used, but more lightweight. https://www.vagrantup.com/intro/vs/docker
