### ISSUE TITLE
Avoid saving images, command line arguments to specify model and categories file

### ISSUE THREAD

**Issue by manjrekarom** [mtobeiyf/keras-flask-deploy-webapp#5]
Hi @mtobeiyf ,

I wanted to ask, why was there a need to save images in the uploads folder?
Also, I think it would be better to specify the path to the model and categories file (with delimeter if needed) rather than changing in the source code file.

I would be happy to send a PR towards these issues if needed.

**Comment by mtobeiyf** [comment]
Actually, it doesn't have to. You can modify the source code directly according to your own needs.
I'd always welcome PRs. However, since this repository serves as a very simple **beginner/toy example** to deploy models, you don't have to make it too powerful and complicated.
For those who have more requirements, they can modify this repo little by little, like you said, command line arguments and etc. But these are not necessary parts in this repo, from my point of view.

**Comment by manjrekarom** [comment]
Oh okay. Got it!

**Comment by mtobeiyf** [comment]
Thanks for your understanding.
